---
# tasks file for ospf
  - name: set OSPF process
    nxos_ospf:
     ospf: "{{ item.ospf_process }}"
     provider: "{{ provider }}"
    with_items: "{{ ospf_router | default([])  }}"

  - name: set OSPF process settings
    nxos_ospf_vrf:
      ospf: "{{ item.ospf_process }}"
      router_id: "{{ item.ospf_router_id }}"      
      vrf: "{{ item.ospf_vrf | default(omit)  }}"
      auto_cost: "{{ item.auto_cost | default(omit)  }}"
      timer_throttle_spf_start: "{{ item.timer_throttle_spf_start | default(omit)  }}"
      timer_throttle_spf_hold: "{{ item.timer_throttle_spf_hold | default(omit)  }}"
      timer_throttle_spf_max: "{{ item.timer_throttle_spf_max | default(omit)  }}"
      timer_throttle_lsa_start: "{{ item.timer_throttle_lsa_start | default(omit)  }}"
      timer_throttle_lsa_hold: "{{ item.timer_throttle_lsa_hold | default(omit)  }}"
      timer_throttle_lsa_max: "{{ item.timer_throttle_lsa_max | default(omit)  }}"
      provider: "{{ provider }}"
    with_items: "{{ ospf_router | default([])  }}"

  - name: set OSPF interfaces
    nxos_interface_ospf:
      interface: "{{ item.interface }}"
      area: "{{ item.ospf_area }}"      
      ospf: "{{ item.ospf_instance }}" 
      provider: "{{ provider }}"
      cost: "{{ item.cost | default(omit)  }}"
      message_digest: "{{ item.message_digest | default(omit)  }}"
      message_digest_algorithm_type: "{{ item.message_digest_algorithm_type | default(omit)  }}"
      message_digest_encryption_type: "{{ item.message_digest_encryption_type | default(omit)  }}"
      message_digest_key_id: "{{ item.message_digest_key_id | default(omit)  }}"
      message_digest_password: "{{ item.message_digest_password | default(omit)  }}"
    with_items: "{{ ospf_interfaces | default([])  }}"

  - name: set OSPF interface network type
    nxos_config:
      lines:
        - ip ospf network {{ item.type }}
      parents: 
        - interface {{item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ ospf_interfaces | default([])  }}"
    when: item.type is defined