---
# tasks file for l3_interfaces
  - name: set port channels
    nxos_portchannel:
      group: "{{ item.group }}"
      members: "{{ item.members }}"
      mode: "{{ item.mode }}"
      state: present
      provider: "{{ provider }}"
    with_items: "{{ portchannels | default([])  }}"

  - name: set physical interfaces
    nxos_interface:
      interface: "{{ item.interface }}"
      description: "{{ item.description | default(omit)}}"      
      admin_state: up
      mode: "{{ item.mode }}"
      provider: "{{ provider }}"
    with_items: "{{ physical_interfaces | default([])  }}"

  - name: set physical interface MTU
    nxos_config:
      lines:
        - mtu {{ item.mtu }}
      parents: interface {{ item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ physical_interfaces | default([])  }}"
    when: item.mtu is defined

  - name: create l3 subinterface using fancy filters to avoid separate vars
    nxos_config:
      lines:
        - interface {{ item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ l3_interfaces | default([])  }}"
    when: item.vlan is defined

  - name: set l3 subinterface using fancy filters to avoid separate vars
    nxos_config:
      lines:
        - encapsulation dot1q {{ item.vlan }}
        - no shutdown
      parents: interface {{ item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ l3_interfaces | default([])  }}"
    when: item.vlan is defined

  - name: set l3 interfaces IP addressing
    nxos_ip_interface:
      interface: "{{ item.interface }}"
      addr: "{{ item.ip_address }}"      
      mask: "{{ item.ip_mask }}"
      tag: "{{ item.tag | default(omit)  }}"
      provider: "{{ provider }}"
    with_items: "{{ l3_interfaces | default([])  }}"

  - name: set l3 interface MTU
    nxos_config:
      lines:
        - mtu {{ item.mtu }}
      parents: interface {{ item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ l3_interfaces | default([])  }}"
    when: item.mtu is defined

  - name: set l3 interface BFD
    nxos_config:
      lines:
        - bfd interval {{ item.bfd_interval }} min_rx {{ item.bfd_min_rx }} multiplier {{ item.bfd_multiplier }}
      parents: interface {{ item.interface }}
      provider: "{{ provider }}"
    with_items: "{{ l3_interfaces | default([])  }}"
    when: item.bfd_interval is defined

  - name: set l3 interfaces multicast
    nxos_pim_interface:
      interface: "{{ item.interface }}"
      state: "{{ item.state }}"      
      sparse: "{{ item.sparse }}"
      provider: "{{ provider }}"
    with_items: "{{ pim_interfaces | default([])  }}"


      
