---
# tasks file for files
  - nxos_file_copy:
      local_file: "{{ item }}"
      provider: "{{ provider }}"
    with_items:
        - "/home/johannlo/ansible/nxosv/files/mtx-device-7_0_3_I6_1.1.0.0-r1705191346.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-grpc-agent-1.0.1-r1705191346.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-infra-1.0.0-r1705191346.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-netconf-agent-1.0.1-r1705191346.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-bgp-7_0_3_I6_1.1.0.0-r1705170158.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-bgp-multiprotocol-7_0_3_I6_1.1.0.0-r1705170136.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-if-ip-7_0_3_I6_1.1.0.0-r1705170202.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-interfaces-7_0_3_I6_1.1.0.0-r1705190423.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-local-routing-7_0_3_I6_1.1.0.0-r1705190305.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-routing-policy-7_0_3_I6_1.1.0.0-r1705190248.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-openconfig-vlan-7_0_3_I6_1.1.0.0-r1705190425.x86_64.rpm"
        - "/home/johannlo/ansible/nxosv/files/mtx-restconf-agent-1.0.1-r1705191346.x86_64.rpm"



